[theme]
base="light"
primaryColor="#1E88E5"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5F5F5"
textColor="#212121"
font="sans serif"

[server]
runOnSave = true

[global]
showWarningOnDirectExecution = false

[runner]
fastReruns = true
