# Generated by Django 5.2.4 on 2025-07-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Phone Verification'), ('reset', 'Password Reset')], default='verify', max_length=10),
            preserve_default=False,
        ),
    ]
