# Generated by Django 5.2.4 on 2025-07-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service_app', '0002_otp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Phone Verification'), ('reset', 'Password Reset')], max_length=20),
        ),
    ]
