# Generated by Django 5.2.4 on 2025-07-23 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service_app', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(default='phone', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
