# Generated by Django 5.2.4 on 2025-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service_app', '0005_otp_phone_number_alter_otp_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_number', 'otp_code', 'purpose'], name='auth_otps_phone_n_c1c19c_idx'),
        ),
    ]
