# Generated by Django 5.0.7 on 2025-07-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service_app", "0006_alter_otp_options_otp_auth_otps_phone_n_c1c19c_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
